name: Intent-classifier-pipeline

on:
  push:
    branches: 
      - kubernetes

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    step 1: 
      - name: checkout repository
        uses: actions/checkout@v4

    Step 2: 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    Step 3: 
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t mlops:latest .
    Step 4: 
      - name: Tag Docker image
        run: |
          docker tag -t ${{ secrets.DOCKER_USERNAME }}/mlops:latest .
    Step 5: 
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

          
      
   
      
  
